#!/bin/bash

# Bash script that displays a list of currently running processes.
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Display process hierarchy using 'ps' command
ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest | head -50

